title: My Knowledge Base
description: Personal notes and documentation
baseurl: ""
url: "https://dholendar27.github.io/obsidian"

theme: minima
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Simple permalink without special characters
permalink: /:title/

# Exclude everything except what we explicitly want
exclude:
  - .obsidian/
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor/
  - node_modules/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - "**/*"

# Only include specific files we want Jekyll to process
include:
  - index.md
  - README.md

# Disable collections for now to avoid URI issues
collections: {}