title: My Knowledge Base
description: Personal notes and documentation
baseurl: ""
url: "https://dholendar27.github.io/obsidian"

theme: minima
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Permalink settings to handle special characters
permalink: /:categories/:title/

# Collections for your note folders
collections:
  dsa:
    output: true
    permalink: /:collection/:name/
  python:
    output: true
    permalink: /:collection/:name/
  docker:
    output: true
    permalink: /:collection/:name/
  sql:
    output: true
    permalink: /:collection/:name/

# Safe mode and encoding
safe: false
encoding: utf-8

exclude:
  - .obsidian/
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor/
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - "**/*&*"
  - "**/*Class & Static Methods*"

# Include only markdown files and standard web assets
include:
  - "*.md"
  - "*.html"
  - "*.css"
  - "*.js"
